### ISSUE TITLE
Please add a `LICENSE` file to this repo

### ISSUE THREAD

**Issue by mbrukman** [Quantum-Flytrap/bra-ket-vue#61]
First of all, thank you for building and sharing this project with us!

The license of the package (per [`package.json`](https://github.com/Quantum-Flytrap/bra-ket-vue/blob/c52201f822a46b664c1c5b0bca2b7efe131b8db9/package.json#L9)) appears to be MIT:

https://github.com/Quantum-Flytrap/bra-ket-vue/blob/c52201f822a46b664c1c5b0bca2b7efe131b8db9/package.json#L9

If that applies to the entire project, could you please add the MIT license in a `LICENSE` file to make that clear?

You can find a copy of the license text here: https://choosealicense.com/licenses/mit/

Thanks!

**Comment by stared** [comment]
@mbrukman Thank you for this remark.

Yes, the whole project is released under MIT license. I added the file, so to make it clear.

**Comment by mbrukman** [comment]
Thanks, @stared!
